const mongoose = require('mongoose')

const candidateSchema=mongoose.Schema({
        candidateName:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        phoneNo:{
            type:String,
            required:true
        },
        address:{
            type:String,
            required:true
        },
        pgCollege:{type:String},
        pgSpecialization:{type:String},
        pgFrom:{type:Number},
        pgTo:{type:Number},
        pgPercentage:{type:Number},
        ugCollege:{type:String},
        ugSpecialization:{type:String},
        ugFrom:{type:Number},
        ugTo:{type:Number},
        ugPercentage:{type:Number},
        sslcSchool:{type:String},
        sslcBoard:{type:String},
        sslcFrom:{type:Number},
        sslcTo:{type:Number},
        sslcPercentage:{type:Number},
        hseSchool:{type:String},
        hseBoard:{type:String},
        hseSpecialization:{type:String},
        hseFrom:{type:Number},
        hseTo:{type:Number},
        hsePercentage:{type:Number},
        skills:[{type:String}],
        skillLevel:[{type:String}],
        internProfile:[{type:String}],
        internOrganization:[{type:String}],
        internLocation:[{type:String}],
        internStartingDate:[{type:Number}],
        internEndingDate:[{type:Number}],
        internDescription:[{type:String}],
        internWFH:[{type:Boolean}],
        jobProfile:[{type:String}],
        jobOrganization:[{type:String}],
        jobLocation:[{type:String}],
        jobStartingDate:[{type:Number}],
        jobEndingDate:[{type:Number}],
        jobDescription:[{type:String}],
        jobWFH:[{type:Boolean}],
        projectTitle:[{type:String}],
        projectStartingDate:[{type:Number}],
        projectEndingDate:[{type:Number}],
        projectDescription:[{type:String}],
        projectLink:[{type:String}]
})
module.exports =mongoose.model('candidates', candidateSchema);